/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 71188bb985312fa5ee6edccbd26856b4)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "RlmLabAgent";
  }
  interface Env {
    LOADER: WorkerLoader;
    AI: Ai;
    RLM_ARTIFACTS: R2Bucket;
    RlmLabAgent: DurableObjectNamespace<import("./src/server").RlmLabAgent>;
  }
}
interface Env extends Cloudflare.Env {}
